version: "3.9"
services:
  api:
    build: .
    ports: ["4000:4000"]
    env_file: .env
    depends_on: [mongo]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
volumes:
  mongo_data:
